### ISSUE TITLE
Would love to be able to play with variables and strings here.

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/reading-ios-variables-and-data-types#4]
Perhaps some directions on using variables and strings with NSLog as part of this readme?

**Comment by AnnJohn** [comment]
Iceboxing for now.

**Comment by markedwardmurray** [comment]
IMO this is answered sufficiently in surrounding code-alongs and it doesn't justify its own lab:

https://github.com/learn-co-curriculum/objc-xcode-warnings-errors
https://github.com/learn-co-curriculum/objc-simple-math
https://github.com/learn-co-curriculum/objc-parrot
