### ISSUE TITLE
Add section about naming variables well

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/reading-ios-variables-and-data-types#5]
Just encountered a public track student using regular phrases to name variables instead of camel case. While there are plentiful examples through the ongoing readings, it would be beneficial to add a section to this reading about how to choose a variable name and that it cannot contain spaces and should be in Camel Case. There is some mention of this in the reading on NSString but it appropriately belongs here.  https://github.com/learn-co-curriculum/reading-ios-things-nsstring-can-do#changing-a-strings-case

**Comment by AnnJohn** [comment]
@markedwardmurray If you're not working on this right now, can you unassign yourself and icebox it?

**Comment by markedwardmurray** [comment]
i might be addressing this along with a curriculum-track issue early next week

https://github.com/learn-co-curriculum/mobile-development-with-ios-track/issues/6
